/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentUpdateManyWithoutDoctorsInput } from "./AppointmentUpdateManyWithoutDoctorsInput";
import {
  ValidateNested,
  IsOptional,
  IsNumber,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { ScheduleUpdateManyWithoutDoctorsInput } from "./ScheduleUpdateManyWithoutDoctorsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DoctorUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  consultationFee?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => ScheduleUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => ScheduleUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => ScheduleUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  schedules?: ScheduleUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialization?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { DoctorUpdateInput as DoctorUpdateInput };
